
teamFormations = {
              "3-4-1-2" : ["GK", "CB", "CB", "CB",
                           "LM", "CM", "CM", "RM",
                           "CAM", "ST", "ST"],
              "3-4-2-1" : ["GK", "CB", "CB", "CB",
                           "LM", "CM", "CM", "RM",
                           "LF", "RF", "ST"],
              "3-4-3" : ["GK", "CB", "CB", "CB",
                           "LM", "CM", "CM", "RM",
                           "LW", "RW", "ST"],
              "3-5-2" : ["GK", "CB", "CB", "CB",
                           "LM", "CDM", "CDM", "RM",
                           "CAM", "ST", "ST"],
              "4-1-2-1-2 Wide" : ["GK", "LB", "CB", "CB",
                           "RB", "CDM", "LM", "RM",
                           "CAM", "ST", "ST"],
              "4-1-2-1-2" : ["GK", "LB", "CB", "CB",
                           "RB", "CDM", "CM", "CM",
                           "CAM", "ST", "ST"],
              "4-1-4-1" : ["GK", "LB", "CB", "CB",
                           "RB", "CDM", "LM", "CM",
                           "CM", "RM", "ST"],
              "4-2-2-2" : ["GK", "LB", "CB", "CB",
                           "RB", "CDM", "CDM", "CAM",
                           "CAM", "ST", "ST"],
              "4-2-3-1" : ["GK", "LB", "CB", "CB",
                           "RB", "CDM", "CDM", "CAM",
                           "CAM", "CAM", "ST"],
              "4-2-3-1 Wide" : ["GK", "LB", "CB", "CB",
                           "RB", "CDM", "CDM", "LM",
                           "CAM", "RM", "ST"],
              "4-3-1-2" : ["GK", "LB", "CB", "CB",
                           "RB", "CM", "CM", "CM",
                           "LF", "RF", "ST"],
              "4-3-3" : ["GK", "LB", "CB", "CB",
                           "RB", "CM", "CM", "CM",
                           "LW", "ST", "RW"],
              "4-3-3 HOLD" : ["GK", "LB", "CB", "CB",
                           "RB", "CDM", "CM", "CM",
                           "LW", "ST", "RW"],
              "4-3-3 DEFEND" : ["GK", "LB", "CB", "CB",
                           "RB", "CDM", "CDM", "CM",
                           "LW", "ST", "RW"],
              "4-3-3 ATTACK" : ["GK", "LB", "CB", "CB",
                           "RB", "CM", "CM", "CAM",
                           "LW", "ST", "RW"],
              "4-3-3 FALSE 9" : ["GK", "LB", "CB", "CB",
                           "RB", "CDM", "CM", "CM",
                           "CF", "LW", "RW"],
              "4-4-1-1" : ["GK", "LB", "CB", "CB",
                           "RB", "LM", "CM", "CM",
                           "RM", "CF", "ST"],
              "4-4-2" : ["GK", "LB", "CB", "CB",
                           "RB", "LM", "CM", "CM",
                           "RM", "ST", "ST"],
              "4-4-2 DEFEND" : ["GK", "LB", "CB", "CB",
                           "RB", "CDM", "CDM", "LM",
                           "RM", "ST", "ST"],
              "4-5-1" : ["GK", "LB", "CB", "CB",
                           "RB", "LM", "CM", "RM",
                           "CAM", "CAM", "ST"],
              "4-5-1 (2)" : ["GK", "LB", "CB", "CB",
                           "RB", "LM", "CM", "CM",
                           "CM", "RM", "ST"],
              "5-2-1-2" : ["GK", "LWB", "CB", "CB",
                           "CB", "RWB", "CM", "CM",
                           "CAM", "ST", "ST"],
              "5-2-2-1" : ["GK", "LWB", "CB", "CB",
                           "CB", "RWB", "CM", "CM",
                           "CAM", "ST", "ST"],
              "5-2-1-2" : ["GK", "LWB", "CB", "CB",
                           "CB", "RWB", "CM", "CM",
                           "LW", "ST", "RW"],
              "5-3-2" : ["GK", "LWB", "CB", "CB",
                           "CB", "RWB", "CM", "CM",
                           "CM", "ST", "ST"]
              }